# Generated by Django 3.0.5 on 2022-09-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaulNewsCategory',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(default='world', max_length=20)),
                ('lang', models.CharField(default='en', max_length=20)),
                ('sort', models.CharField(default='relevancy', max_length=20)),
            ],
        ),
    ]
