# Generated by Django 3.0.5 on 2022-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=20)),
                ('article', models.TextField()),
                ('title', models.TextField()),
                ('img', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
    ]
