# Generated by Django 3.0.5 on 2022-09-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('last_login_data', models.DateField()),
            ],
        ),
    ]
